#!/usr/bin/env bash
# Build the C firmware images and emit lib/*_firmware.ml (OCaml int arrays of
# the program images) so the testbenches need no file dependency.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
CC="${RISCV_CC:-riscv32-unknown-elf-gcc}"
OBJCOPY="${RISCV_OBJCOPY:-riscv32-unknown-elf-objcopy}"

cd "$here"

build() {
  local name="$1"
  shift
  "$CC" -march=rv32i -mabi=ilp32 -nostdlib -nostartfiles -ffreestanding -O2 \
    -Wl,--build-id=none -T link.ld -o "$name.elf" crt0.S "$@"
  "$OBJCOPY" -O binary "$name.elf" "$name.bin"
  local size pad
  size=$(stat -c%s "$name.bin")
  pad=$(( (4 - size % 4) % 4 ))
  if [ "$pad" -ne 0 ]; then head -c "$pad" /dev/zero >> "$name.bin"; fi
  {
    echo "(* Generated by firmware/build.sh -- do not edit by hand. *)"
    echo "let $name : int array ="
    echo "  [|"
    od -An -v -tx4 "$name.bin" \
      | tr -s ' ' '\n' \
      | sed -n 's/^\([0-9a-f]\{8\}\)$/    0x\1;/p'
    echo "  |]"
  } > "$here/../lib/${name}_firmware.ml"
  echo "wrote lib/${name}_firmware.ml from $(stat -c%s "$name.bin") bytes"
}

build hello main.c
build can can.c
build can_rx can_rx.c can_rx_asm.S
build i2c_slave i2c_slave.c
build spi_slave spi_slave.c
build uart_tx_p uart_tx_p.c
build uart_rx_p uart_rx_p.c
build can_err can_err.c
build onewire onewire.c
