#!/usr/bin/env bash
# Build the C firmware and emit lib/c_firmware.ml (an OCaml int array of the
# program image) so the testbench can load it without a file dependency.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
CC="${RISCV_CC:-riscv32-unknown-elf-gcc}"
OBJCOPY="${RISCV_OBJCOPY:-riscv32-unknown-elf-objcopy}"

cd "$here"
"$CC" -march=rv32i -mabi=ilp32 -nostdlib -nostartfiles -ffreestanding -O2 \
  -Wl,--build-id=none -T link.ld -o hello.elf crt0.S main.c
"$OBJCOPY" -O binary hello.elf hello.bin

# pad to a whole number of words
size=$(stat -c%s hello.bin)
pad=$(( (4 - size % 4) % 4 ))
if [ "$pad" -ne 0 ]; then head -c "$pad" /dev/zero >> hello.bin; fi

{
  echo "(* Generated by firmware/build.sh -- do not edit by hand. *)"
  echo "let hello : int array ="
  echo "  [|"
  od -An -v -tx4 hello.bin \
    | tr -s ' ' '\n' \
    | sed -n 's/^\([0-9a-f]\{8\}\)$/    0x\1;/p'
  echo "  |]"
} > "$here/../lib/c_firmware.ml"

echo "wrote lib/c_firmware.ml from $(stat -c%s hello.bin) bytes"
